### ISSUE TITLE
Key size check in getHashRS() in algo_rs.go is invalid

### ISSUE THREAD

**Issue by nikkomega** [cristalhq/jwt#113]
For "RS512", for example, it looks like it's checking that the provided private key's size is 512; the 512 there is the SHA hash size, and is unrelated to the RSA key being used.

https://datatracker.ietf.org/doc/html/rfc7518#page-8

It's bombing out incorrectly when I attempt to use a 2048 RSA key (with a keySize() of 256) with RS512, which should be fine.

**Comment by cristaloleg** [comment]
Interesting, I will take a look today. Can you share a key for this example? (or better - show how to generate one)

**Comment by nikkomega** [comment]
```
key, _ := rsa.GenerateKey(rand.Reader, 2048)
signer, err := jwt.NewSignerRS(jwt.RS512, key)
```

**Comment by cristaloleg** [comment]
Have created https://github.com/cristalhq/jwt/pull/114 but before a merge would like to re-check other algorithms and RFCs.

**Comment by cristaloleg** [comment]
Sorry for a looooong delay. Have removed this validation, v3.1.0 is released https://github.com/cristalhq/jwt/releases/tag/v3.1.0

(will take a look during `v4` which I'm planing to finish this month)
