### ISSUE TITLE
Add clear warnings for HS256 secret length

### ISSUE THREAD

**Issue by lil5** [cristalhq/jwt#121]
https://auth0.com/blog/brute-forcing-hs256-is-possible-the-importance-of-using-strong-keys-to-sign-jwts/

> The second key, secret is 48-bit. This is simply too short to be a valid key. In fact, the JSON Web Algorithms RFC 7518 states that a key of the same size as the hash output (for instance, 256 bits for "HS256") or larger MUST be used with the HS256 algorithm.
> 
> I therefore recommend that anyone trying to generate a JSON Web token and signing them with HS256 to use a properly sized secret key. Auth0 secret keys are 512 bits in length and not susceptible to this type of brute force attack. 

I see too many examples using `secret` as a key without any warnings, please consider adding an example how to generate such key.

**Comment by cristaloleg** [comment]
Hi @lil5 very good point, will take care of it. Also feel free to PR if you want to 😉

**Comment by lil5** [comment]
If this is not a PR of this projects scope I guess a warning on the readme would be good.

Maybe something like:

> **:warning: Create a key for HS256 of at least 256 bits!**
> the RFC7518 standard states that "A key of the same size as the hash output (for instance, 256 bits for "HS256") or larger MUST be used with this algorithm."
> 
> _tldr;_ Create your key for HS256 of 32 bytes long using `crypto/random`

**Comment by cristaloleg** [comment]
Will take care to add it to the README this week (now leaving till Friday)

**Comment by lil5** [comment]
@cristaloleg reminder :wink:

**Comment by cristaloleg** [comment]
Ouch...

**Comment by cristaloleg** [comment]
Done and v4 finally released. I'm really sorry for the delay but shit happens.
