### ISSUE TITLE
Optimisation causing incorrect header to encode

### ISSUE THREAD

**Issue by stevenj** [cristalhq/jwt#33]
encodeHeader in build.go checks if the header is a JWT, and then chooses a pre-encoded header as the result, as an optimization.  However, a Header can also have a `cty` field or a `kid` field.  AND, if either of these are set, the optimization will not encode them.

I Suggest the `if header.Type` check also needs to ensure cty and kid are not set.

This is the function in question.
```go
func encodeHeader(header *Header) []byte {
	if header.Type == "JWT" {
		switch header.Algorithm {
		case NoEncryption:
			return []byte("eyJhbGciOiJub25lIn0")
		case EdDSA:
			return []byte("eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9")
```

**Comment by cristaloleg** [comment]
Yep, confirmed. Thanks for sharing, sadly I haven't used header with additional `kid` and `cty` and this case was uncovered. 

I think about extending if with 2 additional checks:

`if header.Type == "JWT" && header.KeyID == "" && header.ContentType == "" {`

Is it okay for you if I'll fix it tomorrow and add more test?

**Comment by stevenj** [comment]
Yes, that's exactly what i was thinking needed to be done.

**Comment by cristaloleg** [comment]
Hi @stevenj if you've any suggestions for v2 please add them here :) https://github.com/cristalhq/jwt/issues/39
