### ISSUE TITLE
v2 preparations

### ISSUE THREAD

**Issue by cristaloleg** [cristalhq/jwt#39]
- fix and simplify validations
- verify RFC for time format
- ...

**Comment by stevenj** [comment]
One suggestion is to expose the raw signing part of the code, in essence the signPayload function.  I have really specific requirements for my jwt's and (for encoding) it would be easier for me, to just call a function like `signPayload` with two json strings, one for the header + one for the body.  It base64 encodes them, appends them, signs them and returns the result.  Yes it's up to the caller to get the formats right, but for someone who wants to do something unusual, it would be a powerful feature.

**Comment by cristaloleg** [comment]
Well, sounds interesting, but I'm aware that this method will be used too rare, to be exported.

**Comment by cristaloleg** [comment]
BTW: it's happening in #40
