### ISSUE TITLE
Add tests for HS256, HS384 and HS512 

### ISSUE THREAD

**Issue by cristaloleg** [cristalhq/jwt#4]

**Comment by KamalashreeNagaraj** [comment]
Hey, can provide more details about what kind of tests you need?
I can pick this up.

**Comment by cristaloleg** [comment]
Hi @KamalashreeNagaraj 

I thought about unit tests, something simple:
- create signer with some key
- create claims (standard will be enough)
- build a token
- verify the sign

I think 1 test per HS256, HS384 and HS512 will be enough. In the next PRs we can extend if it will be needed 😉

**Comment by KamalashreeNagaraj** [comment]
sure 👍

**Comment by KamalashreeNagaraj** [comment]
Have raised a PR for the same
https://github.com/cristalhq/jwt/pull/12
Please share feedback :)
