### ISSUE TITLE
KeyID support for RFC7517

### ISSUE THREAD

**Issue by danikarik** [cristalhq/jwt#83]
Hi!

I've created PR in [Centrifigo](https://github.com/centrifugal/centrifugo/pull/410/) which uses your package as a dependency. What I'm trying to add is support for JWKS where encryption keys are rotating and to fetch appropriate public key `kid` header is used. [See RFC](https://tools.ietf.org/html/rfc7517#section-4.5)

There is a problem with current `Header` which doesn't contain KeyID property. Previously it was presented in https://github.com/centrifugal/centrifugo/pull/410/.

I can create PR for that.

**Comment by cristaloleg** [comment]
Hi @danikarik thank you for the PR. I'm aware of this issue in Centrifugo, so big thank you for fixing it.

There is one little problem....I've merged things to the master on a way to `v4`. Today I'll try to cleanup a bit and I might ask you to rebase your change (probably without any conflict). Hopefully you'll understand my point :)
