### ISSUE TITLE
Error in readme -> Parse and verify token exemple

### ISSUE THREAD

**Issue by DipandaAser** [cristalhq/jwt#98]
In Parse and verify token exemple line 12. 
is actually ```golang err = verifier.Verify(token)``` but is doesn't work because Verify Need two arguments.
We can replace with ```golang err = verifier.Verify(token.Payload(), token.Signature())```

**Comment by cristaloleg** [comment]
Hi @DipandaAser sorry for the trouble. Yes, I've merged README for the upcoming v4 slightly earlier, so for now (v3) it's `verifier.Verify(token.Payload(), token.Signature())` as you've mentioned.

I will update README or if you want to you can make a PR.

**Comment by DipandaAser** [comment]
Okay i will make a PR @cristaloleg
